steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - backend/Dockerfile
      - -t
      - ${_IMAGE_URI}
      - backend

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_IMAGE_URI}

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE}
      - --image=${_IMAGE_URI}
      - --region=${_REGION}
      - --platform=managed
      - --quiet

substitutions:
  _REGION: europe-west9
  _SERVICE: suestudy
  _AR_REPO: cloud-run-source-deploy
  _IMAGE_URI: ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_AR_REPO}/${_SERVICE}:${COMMIT_SHA}

images:
  - ${_IMAGE_URI}

options:
  logging: CLOUD_LOGGING_ONLY
  dynamic_substitutions: true
